# Generated by Django 3.2.8 on 2021-11-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
