# Generated by Django 3.2.8 on 2021-11-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.courses'),
            preserve_default=False,
        ),
    ]
